// Application
export const LOAD_WEBSITE = "LOAD_WEBSITE";
export const LOAD_WEBSITE_SUCCESS = "LOAD_WEBSITE_SUCCESS";

// Navigation
export const CLOSE_SIDEBAR_MENU = "CLOSE_SIDEBAR_MENU";
export const OPEN_SIDEBAR_MENU = "OPEN_SIDEBAR_MENU";
export const TOGGLE_SIDEBAR_MENU = "TOGGLE_SIDEBAR_MENU";
export const LOAD_SIDEBAR_MENU = "LOAD_SIDEBAR_MENU";
export const UPDATE_MENU_SELECTION = "UPDATE_MENU_SELECTION"